---
- name: Install for macOS
  ansible.builtin.include_tasks: macos.yaml
  when: ansible_distribution == "MacOSX"

- name: Ensure .bashrc.d directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.bashrc.d"
    state: directory
    mode: "0755"

- name: Copy .bashrc config
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: u=rw,g=r,o=r
  loop:
    - src: bashrc
      dest: "{{ ansible_facts['user_dir'] }}/.bashrc"
    - src: bashrc.d/
      dest: "{{ ansible_facts['user_dir'] }}/.bashrc.d"
