---
- name: Install vscode
  community.general.snap:
    name: code
    classic: true
  become: true

- name: Define vscode binary path
  ansible.builtin.set_fact:
    vscode_bin: "{{ vscode_binary_linux }}"

- name: Copy config
  ansible.builtin.copy:
    src: settings.json
    dest: "{{ vscode_config_path_linux }}/settings.json"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: u=rw,g=r,o=r
