---
- name: Install for macOS
  ansible.builtin.include_tasks: install_macos.yaml
  when: ansible_distribution == "MacOSX"

- name: Install for Ubuntu
  ansible.builtin.include_tasks: install_ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- name: Install kubectx
  ansible.builtin.include_tasks: kubectx.yaml

- name: Copy bashrc config
  ansible.builtin.copy:
    src: kubectl.bash
    dest: "{{ ansible_facts['user_dir'] }}/.bashrc.d/kubectl.bash"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: u=rw,g=r,o=r
