---
- name: Install git tools
  ansible.builtin.apt:
    name:
      - git
      - tig
    state: present
  become: true

- name: Copy config
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: "{{ caller_user.stdout }}"
    group: "{{ caller_group.stdout }}"
    mode: u=rw,g=r,o=r
  loop:
    - src: gitconfig
      dest: '{{ ansible_env.HOME }}/.gitconfig'
    - src: gitconfig.d/
      dest: '{{ ansible_env.HOME }}/.gitconfig.d'
    - src: bashrc.git.sh
      dest: '{{ ansible_env.HOME }}/.bashrc.d/git.sh'
