---
- name: Create tmp path for Dockerbuild
  ansible.builtin.file:
    path: "{{ tmp_path }}/jupyter-image"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Move files to docker build context path
  ansible.builtin.copy:
    src: "docker"
    dest: "{{ tmp_path }}/jupyter-image"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Build jupyter image
  community.docker.docker_image:
    build:
      path: "{{ tmp_path }}/jupyter-image/docker"
    name: local-jupyter
    tag: latest
    source: build

- name: Install `jupyterctl`
  ansible.builtin.copy:
    src: "jupyterctl"
    dest: "/usr/local/bin/jupyterctl"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: u=rwx,g=rx,o=rx
  become: true
